# Generated by Django 3.1.6 on 2022-03-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Open'), (2, 'Close'), (3, 'In Progress')], default=0, null=True),
        ),
    ]
