# Generated by Django 3.1.6 on 2022-03-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugapp', '0004_auto_20220319_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
